### ISSUE TITLE
Outdated/unavailable contacts

### ISSUE THREAD

**Issue by Saiv46** [siranweb/activitypub-types#4]
From [README.md](https://github.com/siranweb/activitypub-types/blob/main/README.md#L24)
```md
You can contact me via [matrix](https://matrix.to/#/@siranweb:matrix.org) or [telegram](https://t.me/siranweb)
```

- Matrix: No answer.
- Telegram: User does not exist.

**Comment by siranweb** [comment]
Yeah, I'll remove it. GH issues tab is enough
